export const STORES: { id: number | null; name: string }[] = [
    { id: null, name: 'All Stores' },
    { id: 1,    name: 'Ajax' },
    { id: 2,    name: 'Barrie' },
    { id: 4,    name: 'Brampton' },
    { id: 67,   name: 'Brossard' },
    { id: 3,    name: 'Burlington' },
    { id: 56,   name: 'Burnaby' },
    { id: 66,   name: 'Cambridge' },
    { id: 57,   name: 'Coquitlam' },
    { id: 5,    name: 'Etobicoke' },
    { id: 60,   name: 'Gatineau' },
    { id: 62,   name: 'Halifax' },
    { id: 8,    name: 'Hamilton' },
    { id: 9,    name: 'Kanata' },
    { id: 11,   name: 'Kingston' },
    { id: 12,   name: 'Laval' },
    { id: 75,   name: 'Lawrence Plaza' },
    { id: 71,   name: 'London Masonville' },
    { id: 68,   name: 'Marche Central' },
    { id: 17,   name: 'Markham Unionville' },
    { id: 15,   name: 'Mississauga' },
    { id: 46,   name: 'Montreal Downtown' },
    { id: 18,   name: 'Newmarket' },
    { id: 64,   name: 'North York' },
    { id: 69,   name: 'Oakville' },
    { id: 23,   name: 'Oshawa' },
    { id: 44,   name: 'Ottawa Downtown' },
    { id: 20,   name: 'Ottawa Merivale' },
    { id: 21,   name: 'Ottawa Orleans' },
    { id: 73,   name: 'QC Vanier' },
    { id: 58,   name: 'Richmond' },
    { id: 26,   name: 'Richmond Hill' },
    { id: 27,   name: 'St Catharines' },
    { id: 72,   name: 'Surrey' },
    { id: 28,   name: 'Toronto Downtown' },
    { id: 29,   name: 'Toronto Kennedy' },
    { id: 51,   name: 'Vancouver Broadway' },
    { id: 32,   name: 'Vaughan' },
    { id: 33,   name: 'Waterloo' },
    { id: 34,   name: 'Whitby' },
];
